/**
 * Complete SEO Integration - All Skills Combined
 * Combines: seo, core-web-vitals, performance, wp-rest-api skills
 *
 * For Bengkel Wiguna headless WordPress site
 */

import { extractRankMathSEO, generateRankMathMetadata, type RankMathSEO } from './rank-math-seo'
import { generateOrganizationSchema, generateLocalBusinessSchema, generateServiceSchema, generateArticleSchema, generateFAQSchema, generateBreadcrumbSchema, generateWebSiteSchema } from './seo'
import { generateSpeculationRules } from './core-web-vitals'

// ============================================
// COMBINED SEO UTILITIES
// ============================================

export interface SEOPageConfig {
  seo: RankMathSEO
  pageType: 'homepage' | 'post' | 'page' | 'service' | 'archive'
  slug: string
  baseUrl: string
  breadcrumbs?: Array<{ name: string; url: string }>
}

/**
 * Generate complete SEO metadata for a page
 * Combines Rank Math + custom schemas
 */
export function generateCompleteSEO(config: SEOPageConfig) {
  const { seo, pageType, slug, baseUrl, breadcrumbs } = config

  // Base metadata from Rank Math
  const metadata = generateRankMathMetadata(seo, `${baseUrl}/${slug}`)

  // Additional structured data
  const schemas: Record<string, unknown>[] = []

  // Add schemas based on page type
  switch (pageType) {
    case 'homepage':
      schemas.push(generateWebSiteSchema())
      schemas.push(generateLocalBusinessSchema())
      schemas.push(generateOrganizationSchema())
      break

    case 'post':
      schemas.push(generateArticleSchema({
        title: seo.title,
        slug,
        excerpt: seo.description,
        date: seo.publishedTime || '2024-01-01T00:00:00Z',
      }))
      break

    case 'service':
      schemas.push(generateServiceSchema({
        id: 0,
        title: seo.title,
        slug,
        excerpt: seo.description,
      }))
      break

    case 'archive':
      // Archives don't need specific schemas
      break

    default:
      // Pages get basic organization schema
      schemas.push(generateOrganizationSchema())
  }

  // Add breadcrumb schema if provided
  if (breadcrumbs && breadcrumbs.length > 0) {
    schemas.push(generateBreadcrumbSchema(breadcrumbs))
  }

  // Add FAQ schema if present in Rank Math data
  if (seo.schema?.['@type'] === 'FAQPage') {
    schemas.push(seo.schema)
  }

  // Add AI Custom Schema if generated by BW Headless CMS Agent
  if (seo.schema?.bw_ai_custom_schema) {
    schemas.push(seo.schema.bw_ai_custom_schema as Record<string, unknown>)
  }

  return {
    metadata,
    schemas,
    specluationRules: generateSpeculationRules({
      eagerness: 'moderate',
      excludePatterns: ['/booking/*', '/checkout/*', '/admin/*'],
    }),
  }
}

/**
 * Generate breadcrumbs from URL path
 */
export function generateBreadcrumbsFromPath(path: string, baseUrl: string): Array<{ name: string; url: string }> {
  const segments = path.split('/').filter(Boolean)
  const breadcrumbs: Array<{ name: string; url: string }> = [
    { name: 'Home', url: baseUrl },
  ]

  let currentPath = ''
  const nameMap: Record<string, string> = {
    services: 'Layanan',
    blog: 'Blog',
    lokasi: 'Lokasi',
    contact: 'Kontak',
    tentang: 'Tentang Kami',
  }

  segments.forEach((segment, index) => {
    currentPath += `/${segment}`
    const name = nameMap[segment] || segment.replace(/-/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase())
    breadcrumbs.push({
      name,
      url: `${baseUrl}${currentPath}`,
    })
  })

  return breadcrumbs
}

// ============================================
// SEO PAGE COMPONENT HELPERS
// ============================================

/**
 * Generate Next.js 13+ metadata object
 */
export function generatePageMetadata(config: SEOPageConfig) {
  const { seo, slug, baseUrl, breadcrumbs } = config

  // Generate complete SEO data
  const seoData = generateCompleteSEO(config)

  // Build metadata for Next.js
  return {
    ...seoData.metadata,

    // Additional metadata
    metadataBase: new URL(baseUrl),

    // Format URLs
    alternates: {
      canonical: seo.canonical || `${baseUrl}/${slug}`,
      languages: {
        'id-ID': `${baseUrl}/${slug}`,
      },
    },

    // Note: Google verification is handled in root layout.js via GSC_VERIFICATION const
    // Do NOT duplicate it here to avoid double meta tags

    // Additional metadata if any
    ...(seo.publishedTime && {
      other: {
        'article:published_time': seo.publishedTime,
        'article:modified_time': seo.modifiedTime || seo.publishedTime,
      }
    }),
  }
}

/**
 * Generate JSON-LD script tags for Next.js
 */
export function generateJSONLDScripts(schemas: Record<string, unknown>[]) {
  return schemas.map((schema, index) => ({
    type: 'application/ld+json' as const,
    props: {
      key: `json-ld-${index}`,
      dangerouslySetInnerHTML: {
        __html: JSON.stringify(schema),
      },
    },
  }))
}

/**
 * Generate Speculation Rules script
 */
export function generateSpeculationScript(speculationRules: Record<string, unknown>) {
  return {
    type: 'application/json' as const,
    props: {
      key: 'speculation-rules',
      dangerouslySetInnerHTML: {
        __html: JSON.stringify(speculationRules),
      },
    },
  }
}

// ============================================
// EXAMPLE: HOMEPAGE LAYOUT
// ============================================

export const homepageSEOTemplate = `
// app/(pages)/layout.tsx
import { generateCompleteSEO } from '@/lib/seo-complete'
import { getHomePageData } from '@/lib/wordpress'

export default async function HomeLayout({ children }) {
  // Fetch homepage data
  const data = await getHomePageData()

  // Generate complete SEO
  const seo = extractRankMathSEO(data.pageData)
  const seoData = generateCompleteSEO({
    seo,
    pageType: 'homepage',
    slug: '',
    baseUrl: 'https://bengkelwiguna.com',
  })

  return (
    <>
      {/* JSON-LD Structured Data */}
      {generateJSONLDScripts(seoData.schemas).map((script) => (
        <script key={script.props.key} {...script} />
      ))}

      {/* Speculation Rules for instant navigation */}
      <script
        type="application/speculationrules"
        {...generateSpeculationScript(seoData.speculationRules).props}
      />

      {children}
    </>
  )
}
`

// ============================================
// EXAMPLE: BLOG POST LAYOUT
// ============================================

export const blogPostSEOTemplate = `
// app/blog/[slug]/page.tsx
import { generatePageMetadata, generateBreadcrumbsFromPath } from '@/lib/seo-complete'
import { extractRankMathSEO } from '@/lib/rank-math-seo'
import { generateJSONLDScripts } from '@/lib/seo-complete'

export default async function BlogPost({ params }) {
  const post = await getPostBySlug(params.slug)
  const seo = extractRankMathSEO(post)

  // Generate breadcrumbs
  const breadcrumbs = generateBreadcrumbsFromPath(\`blog/\${post.slug}\`, 'https://bengkelwiguna.com')

  // Generate SEO
  const seoData = generateCompleteSEO({
    seo,
    pageType: 'post',
    slug: \`blog/\${post.slug}\`,
    baseUrl: 'https://bengkelwiguna.com',
    breadcrumbs,
  })

  return (
    <>
      {/* JSON-LD for article */}
      {generateJSONLDScripts(seoData.schemas).map((script) => (
        <script key={script.props.key} {...script} />
      ))}

      {/* Article content */}
      <article>
        <h1>{post.title.rendered}</h1>
        <div dangerouslySetInnerHTML={{ __html: post.content.rendered }} />
      </article>
    </>
  )
}

export async function generateMetadata({ params }) {
  const post = await getPostBySlug(params.slug)
  const seo = extractRankMathSEO(post)

  return generatePageMetadata({
    seo,
    pageType: 'post',
    slug: \`blog/\${post.slug}\`,
    baseUrl: 'https://bengkelwiguna.com',
  })
}
`

// ============================================
// EXAMPLE: SERVICE PAGE LAYOUT
// ============================================

export const serviceSEOTemplate = `
// app/services/[slug]/page.tsx
import { generateCompleteSEO, generateBreadcrumbsFromPath } from '@/lib/seo-complete'
import { extractRankMathSEO } from '@/lib/rank-math-seo'
import { generateServiceSchema } from '@/lib/seo'
import { generateJSONLDScripts } from '@/lib/seo-complete'

export default async function ServicePage({ params }) {
  const service = await getServiceBySlug(params.slug)
  const seo = extractRankMathSEO(service)

  const breadcrumbs = generateBreadcrumbsFromPath(\`services/\${service.slug}\`, 'https://bengkelwiguna.com')

  const seoData = generateCompleteSEO({
    seo,
    pageType: 'service',
    slug: \`services/\${service.slug}\`,
    baseUrl: 'https://bengkelwiguna.com',
    breadcrumbs,
  })

  // Add service-specific schema
  const serviceSchema = generateServiceSchema({
    id: service.id,
    title: service.title.rendered,
    slug: service.slug,
    content: service.content?.rendered,
    featuredImage: service._embedded?.['wp:featuredmedia']?.[0]?.source_url,
  })

  return (
    <>
      {/* LocalBusiness + Service schemas */}
      {generateJSONLDScripts([...seoData.schemas, serviceSchema]).map((script) => (
        <script key={script.props.key} {...script} />
      ))}

      {/* Service content */}
      <div>{service.content.rendered}</div>
    </>
  )
}
`

// ============================================
// EXPORTS
// ============================================

export {
  generateCompleteSEO,
  generateBreadcrumbsFromPath,
  generatePageMetadata,
  generateJSONLDScripts,
  generateSpeculationScript,
  homepageSEOTemplate,
  blogPostSEOTemplate,
  serviceSEOTemplate,
}

// Re-export all SEO utilities
export * from './seo'
export * from './rank-math-seo'
export * from './sitemap'
export * from './core-web-vitals'
export * from './performance'